### ISSUE TITLE
Tracking issue for Grandpa::Authorities

### ISSUE THREAD

**Issue by kvinwang** [Phala-Network/phala-blockchain#1499]
- [ ] Require polkadot and kusama to give us some time. ( @h4x3rotab ? )
- [x] Implementation for compatible code in pruntime with both keys. #1484
- [ ] Implement Concil signed key handover (@kvinwang)
- [x] Upgrade substrate to 1.5 for e3e #1494 
- [ ] Backport the compatible code to pruntime v0.2.x ([#1491](https://github.com/Phala-Network/phala-blockchain/pull/1491)) and v2.1.x ([#1497](https://github.com/Phala-Network/phala-blockchain/pull/1497)) (@kvinwang)
- [ ] Test pruntime with testnet? (@nanometerzhu ?)
- [ ] Publish pruntime v0.2.7 and v2.1.1 (@h4x3rotab ?)
