### ISSUE TITLE
Full chain state sync to pRuntime

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#206]
- [x] Add rpc to substrate for per-block state trie diff dumping (#201)
- [x] Experimental reconstruction of the state trie off-chain
- [x] State trie reconstruct in `pRuntime` (in-mem db) (#213)
- [x] Replace the relayer (`phost`) syncing process (#213)
- [x] Read state from triedb instead of waiting for proactive syncing in system/comp_election.rs (#213)

Misc:

- [x] Docs for relayer (db32479821cb90bcc59dbbea48178d3fe10a6553)
