### ISSUE TITLE
Testnet deployment tracking issue

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-blockchain#23]
- [x] Fix chain parameters: block interval, era interval, base gas fee
- [x] Deploy bootstrap validators
- [x] Deploy public pRuntime
- [x] Release binaries
   - [x] Prepare chain binary with chain-spec
   - [x] pRuntime, phost, and automation scripts
- [x] Tutorials
   - [x] Full node deployment
   - [x] Gatekeeper
- [x] Explorer
   - [x] Basic deployment
   - [x] Fix extrinsic decode
   - [x] Show registered miners
      - [x] Add miner register events
      - [x] Show on frontend
- [x] Activity dashboard
- [x] Faucet bot
- [x] Chain - TEE transferring
   - [x] UI
   - [x] Pass chain to TEE e2e test
   - [x] Pass TEE to chain e2e test
